XLite\Model\Config:
  - name: stripe_sep_1
    category: Iidev\StripeSubscriptions
    type: separator
    orderby: 1000
    translations:
      - code: en
        option_name: "Account settings"
  - name: key
    category: Iidev\StripeSubscriptions
    type: text
    orderby: 1100
    translations:
      - code: en
        option_name: "Publishable key"
  - name: secret_key
    category: Iidev\StripeSubscriptions
    type: text
    orderby: 1200
    translations:
      - code: en
        option_name: "Secret key"
        
controller:
  api:
    - XLite\Module\Iidev\StripeSubscriptions\Controller\API\StripeWebhookController